/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import javax.swing.JOptionPane;

/**
 *
 * @author zhe
 */
public class Main extends javax.swing.JFrame {
    
    int tabungan = 100000;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    public Main(int tabungan) {
        this.tabungan = tabungan;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSaldo = new javax.swing.JButton();
        jbSetor = new javax.swing.JButton();
        jbTarik = new javax.swing.JButton();
        jbKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbSaldo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbSaldo.setText("Info Saldo");
        jbSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(jbSaldo);
        jbSaldo.setBounds(20, 100, 221, 50);

        jbSetor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbSetor.setText("Penyetoran");
        jbSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetorActionPerformed(evt);
            }
        });
        getContentPane().add(jbSetor);
        jbSetor.setBounds(20, 170, 241, 50);

        jbTarik.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbTarik.setText("Penarikan");
        jbTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTarikActionPerformed(evt);
            }
        });
        getContentPane().add(jbTarik);
        jbTarik.setBounds(260, 100, 220, 50);

        jbKeluar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbKeluar.setText("Keluar");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jbKeluar);
        jbKeluar.setBounds(280, 170, 200, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("ATM LALALA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 299, 40);

        setSize(new java.awt.Dimension(534, 294));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaldoActionPerformed
        // TODO add your handling code here:
        new Saldo(tabungan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbSaldoActionPerformed

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Terimakasih telah bertransaksi di ATM LALALA", "Informasi", 1);
        this.dispose();
    }//GEN-LAST:event_jbKeluarActionPerformed

    private void jbTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTarikActionPerformed
        // TODO add your handling code here:
        new Tarik(tabungan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbTarikActionPerformed

    private void jbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetorActionPerformed
        // TODO add your handling code here:
        new Setor(tabungan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JButton jbSaldo;
    private javax.swing.JButton jbSetor;
    private javax.swing.JButton jbTarik;
    // End of variables declaration//GEN-END:variables
}
